version: "3.8"

services:
  caddy:
    image: docker.io/caddy:2.7.4
    restart: unless-stopped
    environment:
      default_site_port: "80"
    volumes:
      - ./env/apps/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy:/data

  lms:
    image: docker.io/overhangio/openedx:21.0.1-indigo
    environment:
      SERVICE_VARIANT: lms
      DJANGO_SETTINGS_MODULE: lms.envs.tutor.production
    restart: unless-stopped
    volumes:
      - ./env/apps/openedx/settings/lms:/openedx/edx-platform/lms/envs/tutor:ro
      - ./env/apps/openedx/config:/openedx/config:ro
      - ./env/apps/openedx/uwsgi.ini:/openedx/uwsgi.ini:ro
      - ./data/lms:/openedx/data
      - ./data/openedx-media:/openedx/media
    depends_on:
      - mysql
      - redis

  mysql:
    image: docker.io/mysql:8.4.0
    command: --character-set-server=utf8mb4 --mysql-native-password=ON
    environment:
      MYSQL_ROOT_PASSWORD: "Hwn2iv1t"
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    image: docker.io/redis:7.4.5
    volumes:
      - ./data/redis:/data

  mongodb:
    image: docker.io/mongo:7.0.28
    volumes:
      - ./data/mongodb:/data/db

  meilisearch:
    image: docker.io/getmeili/meilisearch:v1.8.4
    environment:
      MEILI_MASTER_KEY: "5oY4nJgUGqnA9eoiXzZftsB6"
    volumes:
      - ./data/meilisearch:/meili_data

  cms:
    image: docker.io/overhangio/openedx:21.0.1-indigo
    environment:
      SERVICE_VARIANT: cms
      DJANGO_SETTINGS_MODULE: cms.envs.tutor.production
    volumes:
      - ./env/apps/openedx/settings/cms:/openedx/edx-platform/cms/envs/tutor:ro
      - ./data/cms:/openedx/data

  mfe:
    image: docker.io/overhangio/openedx-mfe:21.0.0-indigo
    volumes:
      - ./env/plugins/mfe/apps/mfe/Caddyfile:/etc/caddy/Caddyfile:ro

  lms-worker:
    image: docker.io/overhangio/openedx:21.0.1-indigo
    command: ["celery", "--app=lms.celery", "worker", "--loglevel=info"]
    volumes:
      - ./data/lms:/openedx/data

  cms-worker:
    image: docker.io/overhangio/openedx:21.0.1-indigo
    command: ["celery", "--app=cms.celery", "worker", "--loglevel=info"]
    volumes:
      - ./data/cms:/openedx/data
