CMS_OAUTH2_SECRET: w3kZ5QHueka7r60AaIZ7jlUr
ID: 0lUU6evCh9hhp8H3YvEWObIp
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEogIBAAKCAQEAi9zwkLYN9QgawsFIfBvvKGdBVPwaJs8wCwBHDiAQpll1a6Gb

  LYAOjWWD9Le3bWstX3Lox+juYszlKG2sLwpDlILwCA+tKypKj+cEEznFcyImZNBd

  VjbshC8KWeMG0abL01ID//NrqtPSTG88WiEIwKGbz3JekyiH1+Z8wbbUZTYNULCU

  jMAafnbK27x96WRASVlk8UcSeXEJtjetVcO+w3b5usOugHYhlmvGwRLonhGzoOkK

  u6JsIdG0o8gynBMNwMyqCYOxRn6rEqxXNJh7vwXhh3wTlsebjqPfCEyUciqpUeE5

  v68mdjEzC779mCt4uDcTGkv/eJXVwgenZyLKVQIDAQABAoIBABIBrHEdFzfsRrG7

  O69K02QSwx0DZgSIGSnZa8x8QViBXPYx9K4LdhQrNS1s968dJNbMjv6p1QMgWQJ2

  +DuIKUI2B1wqVIOhqr7TIbmt7udPRr0k/FdMs++itMT0zxxvyn8W6I/r0XlJUyJn

  EdCSvzM5uzsegOGWTsLzmC1Cch7jgVj9iJTjJuIfatgFzRQ3g1HMQrxBpOsqC6fQ

  vIn0dx/bm2aRIZZ+Fmfd+WoC1I21iVCVclPGuYQeHFzdvDzTX8ML8dYeF9V883n0

  QetgDNlz0hYQuIh78bBvLhHkDeHrn6QJhMZZHAhL+WO7QQgHbGGKh8nVca+PbHtF

  XilEpcECgYEAtbXampGxxJAnrk5bGAJzNwIH8trKGZfUxkKWvcpeJdZzJURrya+U

  67UZ6oddIIbetFT9jYBK/ngedZ0bAkaAAumpmVfakUbs45e0EMxHbgD/K8Icfr3o

  u/ZIzS/qvvRBrnlJ+OlzMo6ZHu2Q30i0agAZeTusE9iN/4tLXkSGILUCgYEAxQtE

  Xnyeee/grBicFtGEqHOsgytOOhrCHnh0w5cT8rG8v7gXO6W62QIus7SwWUE0BzJZ

  kW6V4Dv79VgjcE5N7Gk4q96sW5XHHovFgO5Fm8CGL3yAMdqxFX/IoUdpC/gq+/qc

  9olS7KAv2jyXppPHU5/FFk0WmP3ycf4QRVqJJyECgYAFPYNaZc08n/OlATl7TcbI

  1VQpWsntRwWp2g3C120zpiWX84swO9INoiFnNBQpdfpCNRlC1WpUQF6QgcFfpWzX

  qKltdK0m92apgZx9x4Zf08OIHYb42L03fnjHAhTBAQZL48+QUBs0YAxmae99oPki

  /XG+n0vtHpepwPihdVRw6QKBgD9SeJ04xSEAkp4bpoW6vTv5OHZKw2/uy3VJVpTI

  h1OWBMdD3MuBXgOBLQr5RTbZumOZrakL9cRC4pycv37G20nfIqQxAgjIoF3Toxvk

  9p+wBi9afkQHOKNlFk+mCD8deIrTpf+gb/K1I8upbz7L/OGF1atuCJYP/greD9KJ

  3suhAoGAIITg8BK96UFxm/8RoAVFcmi55dFkdkHEV7nER5Tx6dk1Jg0GJq07c31D

  qm9/h7TRTZVxtffugqjjV1ELDZiMjNyXzxzN8Kt+LweMTsGAl7vN970+/zbarnoP

  BcpA8h38oUTdEpupi8oYKcbmBgDZUk6kizDHUuAE2gDoEl+9CRs=

  -----END RSA PRIVATE KEY-----'
MEILISEARCH_API_KEY: b2d2104f234c618990a77571c32ebfe53099a46beffb8f70c9437cdc204afd2d
MEILISEARCH_API_KEY_UID: 558b7a83-0a91-4604-ad8d-33de10c89c9d
MEILISEARCH_MASTER_KEY: 6s0YTyq7RYosG7juYFPIhyJH
MYSQL_ROOT_PASSWORD: gMGmM5qs
OPENEDX_MYSQL_PASSWORD: F9W1mTy6
OPENEDX_SECRET_KEY: X6hsasqgawJxjJr0oXakfsNZ
PLUGINS:
- mfe
- indigo
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
- https://overhang.io/tutor/contrib
